---
- name: Setup Boilerplate Application
  hosts: all
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - postgresql
          - nginx
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL service is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: stage5buser
        password: securepassword

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: stage5bdb
        owner: stage5buser

    - name: Grant privileges on the database to the user
      become_user: postgres
      postgresql_privs:
        db: stage5bdb
        role: stage5buser
        privs: ALL

    - name: Install Python dependencies
      pip:
        requirements: /opt/stage_5b/requirements.txt
        virtualenv: /opt/stage_5b/venv

    - name: Create log directory
      file:
        path: /var/log/stage_5b
        state: directory
        owner: www-data
        group: www-data

    - name: Configure Nginx
      copy:
        src: /path/to/nginx/config
        dest: /etc/nginx/sites-available/stage_5b
      notify: restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/stage_5b
        dest: /etc/nginx/sites-enabled/stage_5b
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Start the application
      command: /opt/stage_5b/venv/bin/uvicorn main:app --host 127.0.0.1 --port 3000 --log-level info --log-config /opt/stage_5b/uvicorn_log_config.yaml
      args:
        chdir: /opt/stage_5b
      environment:
        PATH: "/opt/stage_5b/venv/bin:{{ ansible_env.PATH }}"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
